# Use uma imagem base do Kali Linux
FROM kalilinux/kali-rolling

# Atualize os pacotes e instale as dependências
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    sudo \
    dbus-x11 \
    xfce4 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Crie um usuário não privilegiado com o mesmo UID/GID do host
RUN useradd -ms /bin/bash -u 1000 kaliuser

# Adicione o usuário ao grupo sudo
RUN usermod -aG sudo kaliuser

# Configuração de autorização do X Server
RUN mkdir -p /tmp/.X11-unix && chmod 1777 /tmp/.X11-unix

# Configuração da variável de ambiente DISPLAY
ENV DISPLAY=:1

# Comando para iniciar a interface gráfica XFCE
CMD ["dbus-launch", "/usr/bin/startxfce4"]
